docs/basic-usage/manually-running-checks.md

After installing the package in a fresh laravel project I referred to this page of the documentation:
https://spatie.be/docs/laravel-health/v1/basic-usage/manually-running-checks
Run the following command:
```
php artisan health:checks
```
Output:
```
Command "health:checks" is not defined.  
Did you mean one of these?               
health:check                         
health:list                          
health:schedule-check-heartbeat    
```
So, fixed the corresponding file for the documentation. Please review.

fix health check artisan command for manually running checks docs

---

docs/storing-results/general.md

The class name provided in the documentation seems to be incorrect. I've updated it to match the class file.

Fix incorrect class name

---

src/Checks/Checks/UsedDiskSpaceCheck.php

The current regular expression, which matches the command line output for the used disk space check, parses a maximum of two digits.
[Example](https://regexr.com/6be7s)
This means that a disk usage of 100% is actually parsed as 00%, which is obviously wrong. I think it is okay to simply parse any digit before the % sign.
[Example](https://regexr.com/6be8b)

Fix regular expression for used disk space check output

---

config/health.php
docs/installation-setup.md

Following on from https://github.com/spatie/laravel-health/pull/16 — this PR fixes a couple of typos I noticed in the docs.

Fix typos in docs

---

resources/views/list.blade.php

When `ray` is only installed as a dev dependency and therefore we're not installing `ray` in a production environment the `@ray` directive is missing.
Just like mentioned in the [ray docs](https://spatie.be/docs/ray/v1/installation-in-your-project/laravel#installing-the-package) 😉

Remove `@ray` from view

---

config/health.php
database/migrations/create_health_tables.php.stub
docs/installation-setup.md
docs/storing-results/in-the-database.md
src/Exceptions/CouldNotSaveResultsInStore.php
src/ResultStores/EloquentHealthResultStore.php

As discussed in https://github.com/spatie/laravel-health/pull/16 — this PR implements a `model` config parameter, for use by the `EloquentHealthResultStore` class.
I followed the general conventions used by http://github.com/spatie/laravel-activitylog for setting custom models — hopefully that's along the right lines this time.
This PR is backwards-compatible.
Thanks! 🙌

Add support for custom HealthCheckResultHistoryItem models

---

config/health.php
docs/configuring-notifications/via-slack.md
docs/installation-setup.md

This PR introduces the configuration change to use the Slack URL located in the `logging.php` config by default.

Use the Logging Slack URL by default

---

resources/lang/en/notifications.php
resources/views/list.blade.php

This PR adds a few translations for a little bit of customization on the health webpage.

More translations support on health status page

---

docs/available-checks/cache.md
docs/available-checks/cpu-load.md
docs/available-checks/db-connection.md
docs/available-checks/debug-mode.md
docs/available-checks/environment.md
docs/available-checks/flare-error-count.md
docs/available-checks/horizon.md
docs/available-checks/ping.md
docs/available-checks/redis.md
docs/available-checks/schedule.md
docs/available-checks/used-disk-space.md
src/Checks/Checks/CacheCheck.php
tests/Checks/CacheCheckTest.php
tests/TestClasses/FakeCacheCheck.php

This PR adds a check for the status of the application cache. This check makes sure the application can connect to your cache system and read/write to the cache keys.
```php
Health::checks([
CacheCheck::new(), // uses the default connection.
CacheCheck::new()->driver('another-cache-driver'),
]);
```

Add Cache Status

---

src/Checks/Checks/FlareErrorOccurrenceCountCheck.php

Due to the change in https://github.com/spatie/laravel-health/pull/8 the url-encoding is no longer necessary. Currently it silently fails (and always shows as `0`) because the Flare API validations fails on the start/end date formatting. Removing the url encoding solves that issue.

Remove url encoding from start/end date in Flare check

---

docs/available-checks/ping.md
src/Checks/Checks/PingCheck.php

I've been using `PingCheck` on my server, but keep finding I get false-positives a few times each day. Whilst 1 second is good for most sites, under certain circumstances, it should allow for customisation.
This backwards-compatible PR allows the default 1-second timeout to be overridden with `PingCheck::new()->timeout(60)`.
Docs have been updated to mention this too 👍

Allow for PingCheck timeout customisation

---

composer.json
resources/views/list-cli.blade.php

Hey guys,
With the addition of `pt`, `pb` and `py` to Termwind, there is no need to add a full div as `padding`.
Hope that helps,
Francisco

Update CLI Output

---

src/Checks/Checks/RedisCheck.php

Bugfixes RedisCheck to take the named connection given by the connectionName parameter

Bugfixes RedisCheck to take the named connection

---

resources/views/list.blade.php

This PR fixes the issue reported in https://github.com/spatie/laravel-health/issues/54. Currently on iOS phones (confirmed in Safari) the page scales down to two columns instead of one:
By adding the viewport meta tag the page will scale down correctly on mobile devices:
I also added the charset meta tag which helps displaying special characters correctly.

Added meta tags for improved (mobile) experience

---

resources/views/list-cli.blade.php
src/Commands/ListHealthChecksCommand.php
tests/Commands/ListChecksCommandTest.php

Hey guys,
This PR adds a new way to show the `health:list` output.
Hope it helps,
Francisco.

feat: Improve `health:list` cli output

---

src/ResultStores/StoredCheckResults/StoredCheckResults.php
tests/ResultStores/StoredCheckResultsTest.php

The results was swapped.
When one of the checks where other then false the allChecksOk returned true and containsFailingCheck returned false.
It should behave the other way
+ Add tests for the functions

Fix allChecksOk and containsFailingCheck behaviour

---

docs/viewing-results/on-the-cli.md
src/Commands/ListHealthChecksCommand.php
tests/Commands/ListChecksCommandTest.php

This PR adds `--fail-command-on-failing-check` option to `health:list artisan` command, so the behaviour is similar to `health:check --fail-command-on-failing-check`.
This is my first PR ever, so I hope I made everything correctly, even if it won't be merged :)
Anyway, thanks for the opportunity to learn something new!

Add --fail-command-on-failing-check to health:list artisan command

---

src/ResultStores/CacheHealthResultStore.php

The `CacheHealthResultStore` expects parameter named `cacheStore`, not `store`. For this reason, changing `file` to a different store did not affect the default configuration.
I had to find out why this results store is not working as expected... Hope this fix helps others save some time 😉

Fix name of the Cache health result store parameter

---

database/migrations/create_health_tables.php.stub

I noticed frequent slow queries being logged in Telescope when running Health Checks on a busy site. This PR solves that problem by adding indexes to the `created_at` and `batch` columns.

Add indexes to Eloquent health check results table

---

.gitattributes

Just went to install this and noticed the size, looks like the `docs` directory is the culprit (due to images). Excluding this from the export reduces the package size from 2.5M to 356K. 👍🏻

chore: exclude docs from package archive

---

src/Checks/Result.php

Successful notifications shouldn't send a notification by default, you can still add one specifically if you want by calling `->notificationMessage()`

Don't set notification message on `ok` by default

---

src/Checks/Checks/ScheduleCheck.php
src/Notifications/CheckFailedNotification.php
src/ResultStores/CacheHealthResultStore.php
tests/ResultStores/CacheHealthResultStoreTest.php

This PR solves the issue that has been raised here https://github.com/spatie/laravel-health/discussions/88
When you specify two channels on your config file only the first one will be trigger. The shouldSend method caches the healthchecks and the second time returns false because it doesn't include the channel name

Failed Notification Cache Per Channel

---

.github/workflows/run-tests.yml
composer.json

Hey,
This PR will add support to PHP 8.0 as it's said in [the docs](https://spatie.be/docs/laravel-health/v1/requirements). Also, will add PHP 8.0 to the tests workflow.

Support PHP 8.0

---

config/health.php
docs/configuring-notifications/via-slack.md
docs/installation-setup.md

This PR fixes an issue with Slack notifications. The `health.notifications.slack.webhook_url` config parameter is always empty when using the `config` helper for `logging.channels.slack.url` because it is not yet set when `health.php` is loaded. Using an env variable is safer and also adds flexibility for distinct Slack webhooks.

Slack notification fix

---

docs/available-checks/ping.md

I noticed there are no mentions of name customization on the `PingCheck`. I thought it's worth mentioning this in the docs since having multiple ping checks will cause a duplication exception thrown.

Add name customization info to ping.md

---

src/Commands/RunHealthChecksCommand.php
tests/Checks/DatabaseConnectionCountCheckTest.php
tests/ResultStores/CacheHealthResultStoreTest.php
tests/ResultStores/EloquentHealthResultStoreTest.php
tests/ResultStores/InMemoryHealthResultStoreTest.php
tests/ResultStores/JsonFileHealthResultStoreTest.php

This PR fixes an issue with storing results using `EloquentHealthResultStore` for skipped checks when a frequency method such as `->everyFiveMinutes()` is used. The `ended_at` field is required and was not set for skipped checks. Also added `ResultStores` tests for skipped checks.

Fix store skipped checks results

---

src/Checks/Checks/UsedDiskSpaceCheck.php
tests/Checks/UsedDiskSpaceCheckTest.php
tests/TestClasses/FakeUsedDiskSpaceCheck.php

Thanks for the package!
On one of our projects we use attached volumes and therefore want to use the UsedDiskSpaceCheck on a custom mount/filesystem.
This PR adds a `filesystemName` property which is used in place of the default (`.`) with `df -P`.

Added filesystemName to UsedDiskSpaceCheck

---

docs/available-checks/ping.md
src/Checks/Checks/PingCheck.php

This PR is helpful when you want to retry the request to make sure a temporary network issue won't cause the check to fail.

Add `retryTimes` method

---

src/HealthServiceProvider.php

Hey 👋
This PR addresses an issue that arises when using [Laravel's Container Events](https://laravel.com/docs/9.x/container#container-events).
Given the following excerpt from an actual `ServiceProvider`:
```php
public function register(): void
{
$this->app->afterResolving(Health::class, $this->registerChecks(...));
}
private function registerChecks(Health $health)
{
$health->checks([
CacheCheck::new(),
// ommitted for brevity...
]);
}
```
Triggering the `health:schedule-check-heartbeat` command makes the application crash with the following exception: 
`Spatie\Health\Exceptions\DuplicateCheckNamesFound`
Digging a bit deeper reveals that the command eventually makes use of the `Health` **Facade** on [L17](https://github.com/spatie/laravel-health/blob/main/src/Commands/ScheduleCheckHeartbea …

Alias `health` in lieu of a separate binding

---

docs/basic-usage/testing.md
src/Facades/Health.php
src/Testing/FakeCheck.php
src/Testing/FakeHealth.php
src/Testing/FakeValues.php
tests/HealthTest.php

Hey all!
If you're a bit of a testing nut, like myself, you want to ensure that your health checks are registered correctly and throw the correct error status when in use. Up to now, this was not possible, because checks cannot be faked and will actually run as they would in production.
To support this feature, I went down a similar route to `Event::fake` in Laravel. That is to say, we swap out the underlying `Health` instance with a `FakeHealth` instance that is able to take fake responses and use them for given health checks.
Here is a basic example:
```php
it('has an error if the database is not available', function () {
Health::fake([
DatabaseCheck::class => new Result(Status::failed())
]);
$this->get('/health')->assertStatus(503);
});
```
There are occasions where it is necessary to …

Adds the ability to fake registered checks.

---

src/Facades/Health.php

Set default argument for the new fake function. This fixes an issue when generating helper file for autocomplete information using barryvdh/laravel-ide-helper.

Minor fix fake default argument

---

.github/workflows/run-tests.yml
src/Checks/Checks/MeiliSearchCheck.php
src/Checks/Checks/PingCheck.php
src/Commands/ListHealthChecksCommand.php
src/Commands/RunHealthChecksCommand.php
src/Health.php
src/Models/HealthCheckResultHistoryItem.php
src/ResultStores/StoredCheckResults/StoredCheckResults.php
tests/Checks/HorizonCheckTest.php
tests/Checks/RedisCheckTest.php

Hello,
I'd like to propose some improvements:
- make the constructor `finishedAt` parameter in the `StoredCheckResults` class explicitly nullable
- change the visibility to protected for some fields in the `MeiliSearchCheck`, `PingCheck` classes
- change the visibility to protected for some fields in the `ListHealthChecksCommand`, `RunHealthChecksCommand` classes
- change the visibility to protected for some fields in the `HealthCheckResultHistoryItem` class
- change the visibility to protected for some fields in the `Health` class
- add skip for Redis-dependent tests when `redis` extension is not available
I've removed the support for PHP 8.2 from this PR and moved it to #141, just not to mix up things.

Some improvements

---

docs/available-checks/overview.md
docs/available-checks/queue.md

As discussed, removing the paragraph about creating a new cache store and added a missing nav item. 
The Queue menu item in the sidebar is the only one that's not alphabetically sorted but I didn't find where you could change this 🤔

Update Queue docs

---

src/Commands/ListHealthChecksCommand.php

So, I am having this issue where the command `artisan health:list --fresh` has an empty output. 
It happens because Termwind has an static variable `$renderer` for it's output and when an Artisan call is made with a command that also uses Termwind this static variable is updated to use `BufferedOutput` instead of the default `ConsoleOutput`.
I could not figure an easy fix for the Termwind project so I'm creating this PR here in order to at least mitigate this issue.

Fix empty output when running `artisan health:list --fresh`

---

docs/available-checks/redis-memory-usage.md
docs/available-checks/schedule.md
docs/available-checks/security-advisories.md
docs/available-checks/used-disk-space.md
src/Checks/Checks/RedisMemoryUsageCheck.php
tests/Checks/RedisMemoryUsageTest.php
tests/TestClasses/FakeRedisMemoryUsageCheck.php

This PR adds a Redis memory usage check. It fails when memory usage reaches a certain threshold.
```php
Health::checks([
RedisMemoryUsageCheck::new()->failWhenAboveMb(500),
]);
```

Add redis memory usage check

---

src/Checks/Checks/DatabaseSizeCheck.php
tests/Checks/DatabaseSizeCheckTest.php
tests/TestClasses/FakeDatabaseSizeCheck.php

The current database size usage is now included in the short summary instead of the `$result->ok()`.

Fix `DatabaseSizeCheck` to not send notifications on passed checks

---

src/Checks/Checks/RedisMemoryUsageCheck.php

This PR is a fix for Redis memory usage check introduced in #154
`info()` returns different array structure depending on the driver used. 
Below is the output when this check was run with phpredis.
> The check named `RedisMemoryUsage` did not complete. An exception was thrown with this message: `ErrorException: Undefined array key "Memory"`

Fix redis memory usage check when phpredis is used

---

README.md

The company rebranded last year and we're in the process of updating vendor names for our public packages.

Update vendor name for Laravel Health Check

---

src/Commands/DispatchQueueCheckJobsCommand.php
tests/Commands/DispatchQueueCheckJobsCommandTest.php

This PR fix dispatch `HealthQueueJob` to queues, defined in multiple checks (not the first one).

Fix dispatch HealthQueueJob for multiple checks

---

src/Support/DbConnectionInfo.php

pg_size_pretty returns prettified string instead of the number, like 123 MB.

postgresql database size fix

---

src/Commands/ListHealthChecksCommand.php
tests/Commands/ListChecksCommandTest.php

When I ran `php artisan health:list --fresh --do-not-store-results --no-notification
` I've got the following error:
```
The "1" argument does not exist.
```
Here's a quick fix.

fix(ListChecksCommand): run multiple options at once

---

src/Support/DbConnectionInfo.php

I've discovered an issue in the `getMySQLDatabaseSize()` method that can lead to PHP warnings about precision loss. Specifically, the MySQL query in this function employs the ROUND() function with one decimal place, sometimes resulting in a float. However, the function's type hint specifies an integer return type, and thus when the float is implicitly converted to an integer, PHP logs a warning about precision loss.
For example:
```shell
Implicit conversion from float-string "7.5" to int loses precision in /var/www/html/vendor/spatie/laravel-health/src/Support/DbConnectionInfo.php on line 60
```
This pull request proposes a simple but effective fix to this problem: adjusting the ROUND() function in the MySQL query to round to the nearest whole number, thereby ensuring that an integer is …

Round MySQL Database Size to Nearest Integer to Prevent Precision Loss

---

docs/basic-usage/conditionally-running-or-modifying-checks.md
docs/viewing-results/general.md
src/Checks/Check.php
tests/HealthTest.php

This would allow adding custom health checks filtering using macros:
```
Check::macro('inProduction', function () {
return $this->if(fn () => app()->isProduction());
});
Check::macro('inContainerTypes', function (array $types) {
return $this->if(fn () => in_array(app()->containerType(), $types));
});
Health::checks([
DebugCheck::new()
->inProduction()
->inContainerTypes(['app']),
]);
```

Make Check macroable and allow chaining callables in if() and unless()

---

src/Checks/Checks/CacheCheck.php

When you set the following in your `.env`
```dotenv
CACHE_DRIVER=null
```
The `\Spatie\Health\Checks\Checks\CacheCheck` will fail because of the typehints. 
`config('cache.default', 'file')` will return `null` and give an error as the typehint there is not nullable.

Support null cache driver

---

src/Support/DbConnectionInfo.php

Per Discussion https://github.com/spatie/laravel-health/discussions/198
> as you can see here:
> 
> https://github.com/spatie/laravel-health/blob/1dee638806b6b2d8971363bf1e26cb17835e2dcb/src/Support/DbConnectionInfo.php#L15
> 
> we're using `show status where variable_name = "threads_connected"` which shows overall server processes not my user-only this is wrong when running several apps on the same server and setting `max_user_connections` to like 60 per app. it should warn me when my user exceeds the limit not the overall server.
> 
> so it should be changed to `SELECT COUNT(*) FROM information_schema.PROCESSLIST;`
> 
> this won't be breaking change for others, as if you're the only user on the server or using root mysql, this will return same data, but if user is shared with other apps …

Mysql Connections Count is not accurate Fixes #198

---

src/Checks/Checks/QueueCheck.php
tests/Checks/QueueCheckTest.php

This is follow-up for #197 
**Problem description**
Queue check doesn't work properly when you name your queue other than `default`.
**Problem details**
The issue is that in laravel the [default queue connection is stored as](https://github.com/laravel/laravel/blob/10.x/config/queue.php#L16) `config('queue.default')`, but this package calls `config('queue. driver')`. As a result, the package cannot find the connection config and selects `default` queue as one to check:
```
protected function getDefaultQueue($connection)
{
return config("queue.connections.{$connection}.queue", 'default');
}
```

Fix getting default queue settings

---

src/Checks/Checks/CacheCheck.php

If you have multiple environments, like subdeployments, and you run the `CacheCheck`, it can cause race conditions, because multiple environments write / read the same cache key (`laravel-health:check`).
By adding the random string from the test cache value to the key itself, we can avoid that race condition.
Also added `Cache->forget()`, so we don't flood the cache with all those randomized keys.

Fixed the CacheCheck causing race conditions in some cases

---

composer.json

I'm trying to upgrade `nunomaduro/collision` to 8.x in my project. This fails because it depends on `nunomaduro/termwind` 2.0 and `spatie/laravel-health` depends on 1.14. 
Termwind drops support for Symfony 5 and 6 and it seems like it drops support for PHP 8.1 as well. I guess that means this package needs to drop support for 8.0 and 8.1 as well?

Update nunomaduro/termwind to 2.0

---

config/health.php
database/migrations/create_health_tables.php.stub
src/Models/HealthCheckResultHistoryItem.php

Hi! This PR introduce the capability for the EloquentHealthResultStore to support a different database connection to store the data. 
The primary motivation behind this enhancement is to enable applications to maintain a clean and focused main database by offloading monitoring logs to a separate database. In many applications, especially those with high traffic or complex data structures, the main database is optimized for performance and critical operations. Monitoring logs, while essential for maintaining the health and performance of the application, can quickly grow in size and potentially clutter the main database. This can lead to decreased performance and complicate database maintenance tasks.
Regards!

Added Different Database Connection Support

---

docs/available-checks/meilisearch.md
src/Checks/Checks/MeiliSearchCheck.php

Most Meilisearch instances are protected with a token (e.g. when you use the cloud version).
There was no way to specify the token for the check, so I’ve added an option to specify it.

Added the option to specify a HTTP Authentication token for the Meilisearch check

---

resources/views/list.blade.php

It seems like the bottom touch end of the page if we have many card monitor

Give space between the bottom card and end of page

---

src/Checks/Checks/MeiliSearchCheck.php

https://github.com/meilisearch/meilisearch/blob/b1844b0c270e6819e1e52a0eaa40cc1c3d9a45fb/meilisearch/src/routes/mod.rs#L282
It seems they changed the response message. This should add `running` as OK-status, but also keep the previous one, just to be backwards compatible.

Add running status to MeiliSearchCheck

---

docs/installation-setup.md

Laravel 11 has no Kernel file in the app anymore, the Schedule for should be set in the routes/console.php

Update installation-setup.md to move schedule command to route/console

---

src/Checks/Checks/BackupsCheck.php
src/Support/BackupFile.php
tests/Checks/BackupsCheckTest.php

This adds support for checking backups on any filesystem you have defined in your Laravel installation. Including for example an S3 bucket. 
The syntax is very simple. Something like this works with [spatie/laravel-backup](https://github.com/spatie/laravel-backup) when backups are saved to S3:
```
BackupsCheck::new()
->onDisk('backups_remote')
->locatedAt(config('backup.backup.name'))
```
I needed to create a new file `BackupFile.php` to abstract away the filesystem from `SymfonyFile` that you used before. This was the best solution to make this backwards compatible and support the glob style syntax in `->locatedAt()`. When using Filesystem disk glob is not available and therefore that is not supported when using a Laravel disk. 
In the next major version I would suggest to stop using …

Add support for checking backups on filesystem disks

---

docs/available-checks/redis-memory-usage.md
src/Checks/Checks/RedisMemoryUsageCheck.php
tests/Checks/RedisMemoryUsageTest.php

Improvements:
- Added `->warnWhenAboveMb()` to set a warning threshold
- Sets memory usage  in summary and meta data

Improve redis memory usage check

---

docs/available-checks/backups.md
src/Checks/Checks/BackupsCheck.php
src/Checks/Result.php
src/Support/BackupFile.php
tests/Checks/BackupsCheckTest.php

We are using the BackupsCheck for Database snapshots from your [laravel-db-snapshots)](https://github.com/spatie/laravel-db-snapshots) package. We have over 200 snapshots in are storing them in a S3 bucket. Thanks for accepting our previous [PR](https://github.com/spatie/laravel-health/pull/237) to allow checking external disks. However, this introduced some performance problems. The way the current BackupsCheck work if first checks the file size of all backup files and then checks the modified date. For each check the check needs to reach out to the external file and fetch that information. This takes somewhere around 0.05 - 0.1 seconds per check per file. With 200 backup files this takes up to about 200 * 2 * 0.1 = 40 seconds. That is obviously not OK. 
This PR addresses that in two …

Performance optimizations for backups check

---

docs/available-checks/overview.md

Update 3rd party checks section at https://spatie.be/docs/laravel-health/v1/available-checks/overview#content-third-party-checks to include a link to my very simple Opcache status health check.

Update 3rd Party Checks List - Opcache check

---

src/Commands/RunHealthChecksCommand.php

I noticed there's an extraneous brace in the crashed message, so I removed it.

Remove typo in crashed message

---

composer.json

support for dependency : `laravel/serializable-closure` version `2.0`,
for this package stops downgrading :
`Downgrading spatie/laravel-health (1.30.1 => 1.29.0)`

bump serializable-closure

---

docs/configuring-notifications/via-oh-dear.md

A fix for a small typo in the documentation (key name for the Oh Dear configuration) as well as some minor phrasing suggestions in that same file.

Fix some typos and suggest improvements in via-oh-dear.md

---

yarn.lock

This resolves security vulnerability issues and notices by updating `tailwindcss` to resolve critical CVE with dependencies like https://nvd.nist.gov/vuln/detail/CVE-2021-44906

Update package to resolve security vulnerability issues

---

src/ResultStores/StoredCheckResults/StoredCheckResult.php

if notificationMessage passed as null error 500 will thrown

Handle nullable for notificationMessage property

---

docs/basic-usage/registering-your-first-check.md

Updated the link to the docs to go to the latest version (v12) instead of old v8

Update link to Laravel docs latest version

---

config/health.php
docs/basic-usage/conditionally-running-or-modifying-checks.md
src/ResultStores/StoredCheckResults/StoredCheckResults.php
tests/ResultStores/StoredCheckResultsTest.php

This PR adds a new configuration option `treat_skipped_as_failure` that allows users to control whether skipped health checks should be considered as failing checks. By default, skipped checks are treated as failures, maintaining the current behavior.
- Added a new configuration option `treat_skipped_as_failure` (defaults to `true`)
- Modified the `containsFailingCheck()` method to respect this configuration
- Added tests to verify both configuration states work as expected
In some environments, users may want to implement more lenient health check policies where skipped checks are not considered failures. This configuration makes the behavior customizable to accommodate different use cases.
This change is fully backward compatible and doesn't introduce any breaking changes. The default …

Add configuration option for treating skipped checks as failures

---

CHANGELOG.md
docs/available-checks/meilisearch.md
docs/available-checks/overview.md
src/Checks/Checks/MeilisearchCheck.php
tests/Checks/MeilisearchCheckTest.php

The capitalization of Meilisearch is without a capital S:
This PR renames all references from `MeiliSearch` to `Meilisearch`. This is not a breaking change as PHP class instantiation is not case sensitive.
Thanks!

rename: fix Meilisearch name

---

src/Checks/Checks/QueueCheck.php

In Carbon 3, the `diffInMinutes()` method returns a float value instead of an integer. When we cast this value to `(int)`, it rounds down the decimal part, which causes the test to fail because the actual time difference is not properly calculated.
Remove the `(int)` cast from line 86 in `QueueCheck.php` to allow the float value to be used directly. This ensures accurate time calculations in both Carbon 2 and Carbon 3.

fix: Remove int casting in QueueCheck for Carbon 3 compatibility
