spatie/laravel-health

docs/viewing-results/as-json-via-an-api.md, docs/viewing-results/on-a-webpage.md
According to `HealthCheckResultsController` controller, The correct check will happen with the key `fresh`:
https://github.com/spatie/laravel-health/blob/35567d44b46d1807d0b3a238a406412b4b31b3a9/src/Http/Controllers/HealthCheckResultsController.php#L18-L20
=> Correct the query parameter in on-a-webpage.md

docs/available-checks/cpu-load.md, docs/introduction.md, docs/viewing-results/general.md
This PR fixes the syntax in the provided documentation.
=> Fix syntax docs on health checks

docs/available-checks/overview.md, docs/basic-usage/registering-your-first-check.md, docs/configuring-notifications/general.md, docs/installation-setup.md
@freekmurze Great job on Laravel Health! Tested all of the links in your docs and fixed the broken links.
=> Fix broken links in docs

src/Http/Controllers/HealthCheckJsonResultsController.php
I'm sorry, I've just noticed the same neighboring PR 🙈
Nevertheless this is the minimal fix
=> Fixed json response header

docs/viewing-results/on-a-webpage.md
that can be used <del>the </del> render the latest results of all checks. Simply use that controller in your routes on any URL you desire.
that can be used to render the latest results of all checks. Simply use that controller in your routes on any URL you desire.
=> Grammar correction

resources/lang/ar/notifications.php
Add Arabic Translation on `lang/ar/notifications.php`
=> Add arabic translation

resources/lang/de/notifications.php, resources/lang/tr/notifications.php
This Pull Request adds German and Turkish Translations.
=> Add German and Turkish Translations

resources/lang/es/notifications.php
=> Add spanish translation

src/Exceptions/CheckDidNotComplete.php, src/Exceptions/CouldNotSaveResultsInStore.php
Today I received an error message, but I don't know which exceptions triggered this error.
=> Get the exception class name

src/Checks/Checks/PingCheck.php
This PR enables us to change HTTP method and headers to a PingCheck.
=> Added method and headers helpers to PingCheck

docs/basic-usage/registering-your-first-check.md, docs/configuring-notifications/via-oh-dear.md
Hi! Two things i got stuck on while reading the docs
- Just a minor misplaced ",".
- Most of the code, like the one below shows the "finished product". Except this one which shows the unchanged version, personally would prefer this way but totally understandable if you do not agree.
Thanks for all your contribution to this community!
=> Minor fix docs

src/Checks/Result.php
Setting $message didn't do anything and discovered this line was missing :)
=> Missing setting $message

.github/workflows/run-tests.yml
Hello,
I've split the #140 to two separate PRs.
This one add support for PHP 8.2.
=> Add support for PHP 8.2

src/Support/DbConnectionInfo.php
$connection->raw() - returns object, not string
=> mysql connection count fix

docs/available-checks/queue.md
`public` => `protected` (like it is in the `Kernel.php`)
=> Just a minor updated in the function type

resources/lang/pt/notifications.php
Simple fix for typo in the portuguese language file.
=> Fix typo in portuguese language file

docs/available-checks/overview.md
Hey! 
Added my third party package for checking queue size to the list. 
Have a nice week end
=> Added Queue Size Check

src/Models/HealthCheckResultHistoryItem.php, tests/Support/DbConnectionInfoTest.php, tests/TestClasses/CrashingHealthCheckResultHistoryItem.php
This fixes and issue added in #216
More information in this discussion: https://github.com/spatie/laravel-health/discussions/218
=> Fix model connection

resources/lang/it/notifications.php
just a typo but it bothered me :D
=> Fix typo in Italian translation

docs/configuring-notifications/via-oh-dear.md
=> Update old docs link

resources/lang/bn/notifications.php
- Fixed minor grammatical issues in Bangla translation.
- Improved readability of health check messages.
- Ensured consistent terminology.
=> Improve Bangla translation

docs/storing-results/in-the-database.md
Update doc to represent latest laravel documentation: https://laravel.com/docs/12.x/eloquent#pruning-models
=> Update prune docs according to current laravel documentation

database/migrations/create_health_tables.php.stub, hey.zip
Fixed some style issues on the migration stub and removed orphan hey.zip which probably should not be in the repo?
=> Cleaned up stub and orphan hey.zip
